namespace Proptech.Core.Enums
{
    public enum MaterialType
    {
        Stonework = 1,
        Concrete = 2,
        Rebar = 3,
        Coupler = 4,
        Pile = 5,
        Soil = 6,
        StructuralSteel = 7,
        SteelAccessory = 8,
        BrickMasonry = 9,
        StoneMasonry = 10,
        Steel = 11,
        Cement = 12,
        PUF = 13,
        Wood = 14,
        GFRG = 15,
        RCC = 16,
        Roofing = 17,
        RoofAccessory = 18,
        SandStoneSlab = 19,
        ThermalInsulationPainting = 20,
        DoorFrame = 21,
        DoorShutter = 22,
        WindowFrame = 23,
        WindowShutter = 24,
        WoodAccessory = 25,
        CurtainRod = 26,
        VisionPanel = 27,
        Scantling = 28,
        PlankAndBoard = 29,
        Flooring = 30,
        Ceiling = 31,
        CeilingAccessory = 32,
        Painting = 33,
        Pointing = 34,
        PrePainting = 35,
        Polishing = 36,
        Pipe = 37,
        PlumbingAccessory = 38,
        SanitaryAccessory = 39,
        Aggregate = 40,
        Bitumen = 41,
        StoneSlab = 42,
        WaterProofingMaterial = 43,
        PolymerCementationCoating = 44,
        Kicker = 45,
        WaterStop = 46,
        SheetAndMembrane = 47,
        Ubeading = 48
    }
}
